name: CI

on:
    push:
    pull_request:
        ranches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        otp_version: [20, 21, 22, 23]

    runs-on: ubuntu-latest

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
